{
 "title": "AVS Specification Metrics",
 "description": "AVS Specification Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "AvsName", "label": "AVS Name", "query": { "query": "label_values(avs_name)" } },
   {
    "name": "TaskType",
    "label": "TaskType",
    "query": {
     "query": "label_values(avs_operator_counter_fetch_task,type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVS Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eigen_performance_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Performance Score",
   "type": "gauge",
   "description": "The performance metric is a score between 0 and 100 and each developer can define their own way of calculating the score. The score is calculated based on the performance of the Node and the performance of the backing services.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eigen_performance_score{avs_name=\"$AvsName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator Metadata",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "avs_operator_counter_metadata{avs_name=\"$AvsName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Attestation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Last Attestation Time",
   "type": "stat",
   "description": "The last attestation time.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avs_operator_const_liveness_ts{avs_name=\"$AvsName\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next Attestation will be",
   "type": "stat",
   "description": "The next submission time for the attestation report.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avs_operator_const_next_attestation_ts{avs_name=\"$AvsName\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attestation Account Available Balance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avs_operator_attestation_acc_balance{avs_name=\"$AvsName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Task Info: $TaskType", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "TaskType" },
  {
   "title": "TaskID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avs_operator_gauge_latest_task{type=\"$TaskType\", avs_name=\"$AvsName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Task Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avs_operator_gauge_process_task_ms{type=\"$TaskType\", avs_name=\"$AvsName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SGX Prover Prove Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avs_prover_gauge_prove_ms{type=\"$TaskType\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SGX Prover Generate Context Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avs_prover_gauge_gen_ctx_ms{type=\"$TaskType\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Economics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Registered Stakes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(quorum_number) (eigen_registered_stakes{avs_name=\"$AvsName\"}) / 1000000000000000000",
     "legendFormat": "${{token}}"
    }
   ]
  },
  {
   "title": "Slashing status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eigen_slashing_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fees Earned",
   "type": "stat",
   "description": "The total fees earned per token.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eigen_fees_earned_total", "legendFormat": "${{token}}" }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "description": "Average Response Time per method in seconds over time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "rate(eigen_rpc_request_duration_seconds_sum{method=~\".*\", avs_name=\"$AvsName\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total RPC Requests",
     "type": "timeseries",
     "description": "Total of JSON-RPC requests per method.",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "eigen_rpc_request_total{avs_name=\"da-node\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Request duration distribution",
     "type": "histogram",
     "description": "Request duration distribution in seconds per method.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(eigen_rpc_request_duration_seconds_count{avs_name=\"$AvsName\"}[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  }
 ]
}