{
 "title": "multi-prover-avs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Operator Latest Task",
   "type": "gauge",
   "description": "Trace the latest task id",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avs_operator_gauge_latest_task", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Aggregator",
   "type": "timeseries",
   "description": "Tasks submitted to the aggregator",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (types) (avs_aggregator_counter_new_task) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (types) (avs_aggregator_counter_fetch_task)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (types) (avs_aggregator_counter_submit_task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (type) (avs_operator_counter_fetch_task)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (avs_operator_counter_submit_task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Latency",
   "type": "timeseries",
   "description": "Latency for RPC calls",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "avs_prover_gauge_rpc_call_ms", "legendFormat": "__auto" },
    {
     "expr": "sum by (method) (avs_aggregator_gauge_rpc_call_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prover",
   "type": "timeseries",
   "description": "POEs fetched from the Prover",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "avs_prover_counter_gen_poe", "legendFormat": "__auto" },
    { "expr": "avs_prover_counter_gen_pob", "legendFormat": "__auto" },
    { "expr": "avs_prover_submit_pob", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task Latency",
   "type": "timeseries",
   "description": "Time taken to do various tasks in ms",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "avs_prover_gauge_gen_pob_ms", "legendFormat": "__auto" },
    { "expr": "avs_prover_gauge_gen_poe_ms", "legendFormat": "__auto" },
    {
     "expr": "sum by (type) (avs_operator_gauge_process_task_ms)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avs_operator_gauge_gen_report_ms",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (type) (avs_aggregator_gauge_bls_aggregation_ms)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Calls",
   "type": "timeseries",
   "description": "Number of calls made to the RPC API (by the prover)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (method) (avs_prover_counter_rpc_call)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Sizes",
   "type": "timeseries",
   "description": "Sizes of different batches",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (types) (avs_aggregator_gauge_task_context_size)",
     "legendFormat": "__auto"
    },
    { "expr": "avs_prover_pob_size", "legendFormat": "__auto" }
   ]
  }
 ]
}