global:
  scrape_interval: 1m

# Set default port for scrapping
scrape_configs:
  - job_name: 'multiprover-avs'
    scrape_interval: 1m
    static_configs:
      - targets: ['multi-prover-operator:15682']
  - job_name: 'multiprover-avs-mainnet'
    scrape_interval: 1m
    static_configs:
      - targets: ['multi-prover-operator-mainnet:15682']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
