networks:
  multiprover-network:
    name: multiprover-avs-network

services:
  operator:
    image: ghcr.io/automata-network/multi-prover-avs/operator:v0.4.0
    restart: always
    container_name: multi-prover-operator
    command: -c /config/operator.json
    ports:
      - "15692:15692"
    expose:
      - 15682
    volumes:
      - ./config:/config
      - "${BLS_KEY_FILE_HOST}:${BLS_KEY_FILE_DOCKER}:readonly"
    working_dir: /
    networks:
      - multiprover-network
